declare namespace NodeJS {
  interface ProcessEnv {
    REACT_APP_API_GET_FIELDS: string;
    REACT_APP_API_GET_FIELD: string;
    REACT_APP_API_GET_TYPES: string;
    REACT_APP_API_POST_FIELD: string;
    REACT_APP_API_PUT_FIELD: string;
    REACT_APP_API_DELETE_FIELD: string;
    REACT_APP_API_POST_RECORD: string;
    REACT_APP_API_PUT_RECORD: string;
    REACT_APP_API_DELETE_RECORD: string;
    REACT_APP_API_GET_RECORD: string;
    REACT_APP_API_TEST_GET_FIELDS: string;
    REACT_APP_API_TEST_GET_FIELD: string;
    REACT_APP_API_TEST_GET_TYPES: string;
    REACT_APP_API_TEST_POST_FIELD: string;
    REACT_APP_API_TEST_PUT_FIELD: string;
    REACT_APP_API_TEST_DELETE_FIELD: string;
    REACT_APP_API_TEST_GET_RECORD: string;
    REACT_APP_API_TEST_POST_RECORD: string;
    REACT_APP_API_TEST_PUT_RECORD: string;
    REACT_APP_API_TEST_DELETE_RECORD: string;
  }
}