import { ApiUrls } from "../models/API";
import {
  API_TEST_GET_FIELDS,
  API_TEST_GET_FIELD,
  API_TEST_GET_TYPES,
  API_TEST_POST_FIELD,
  API_TEST_PUT_FIELD,
  API_TEST_DELETE_FIELD,
  API_TEST_GET_RECORD,
  API_TEST_POST_RECORD,
  API_TEST_PUT_RECORD,
  API_TEST_DELETE_RECORD,
  API_TEST_GET_LENGTH
} from '../../ApiUrls';

export const TestApiUrls: ApiUrls = {
  getFieldsUrl: API_TEST_GET_FIELDS,
  getRecordUrl: API_TEST_GET_RECORD,
  postRecordUrl: API_TEST_POST_RECORD,
  putRecordUrl: API_TEST_PUT_RECORD,
  deleteRecordUrl: API_TEST_DELETE_RECORD,
  getTypesUrl: API_TEST_GET_TYPES,
  postFieldUrl: API_TEST_POST_FIELD,
  putFieldUrl: API_TEST_PUT_FIELD,
  deleteFieldUrl: API_TEST_DELETE_FIELD,
  getLengthUrl: API_TEST_GET_LENGTH,
};